### ISSUE TITLE
[BUG] - Nouvelle installation 0.9.1 (default setup)

### ISSUE THREAD

**Issue by SeepDev** [MyElectricalData/myelectricaldata_import#415]
Installation et premier demarre suivant la documentation d'installation et configuration du [wiki](https://github.com/MyElectricalData/myelectricaldata/wiki/01.-Home) 

- Docker compose 
     m4dm4rtig4n/myelectricaldata:latest
     influxdb:2.4

<details>
<summary>Docker-Compose</summary>

```yaml

version: "3"
services:
  myelectricaldata:
    image: m4dm4rtig4n/myelectricaldata:latest
    restart: unless-stopped
    volumes:
      - ./data:/data
    environment:
      TZ: Europe/Paris
    ports:
            - '5000:5000'
    links:
            - influxdb

  influxdb:
    image: influxdb:2.4
    ports:
      - '8086:8086'
    volumes:
      - ./../data/influxdb:/var/lib/influxdb2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://influxdb:8086"]
      interval: 25s
      timeout: 3s
      retries: 5
    environment:
      TZ: Europe/Paris
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: myelectricaldata
      DOCKER_INFLUXDB_INIT_PASSWORD: myelectricaldata
      DOCKER_INFLUXDB_INIT_ORG: myelectricaldata
      DOCKER_INFLUXDB_INIT_BUCKET: myelectricaldata
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: myelectricaldata



```
</details>
<details>
<summary>Configuration (config.yaml)</summary>

```yaml

debug: true
wipe_cache: false
wipe_influxdb: false
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: false
influxdb:
  batching_options:
    batch_size: 1000
    exponential_base: 2
    flush_interval: 1000
    jitter_interval: 0
    max_retries: 5
    max_retry_delay: 125000
    max_retry_time: 180000
    retry_interval: 5000
  bucket: myelectricaldata
  enable: true
  hostname: influxdb
  method: synchronous
  org: myelectricaldata
  port: 8086
  token: myelectricaldata
log2file: false
mqtt:
  client_id: myelectricaldata
  enable: false
  hostname: mosquitto
  password: null
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: null
myelectricaldata:
  ------------:
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: '2023-03-15'
    consumption_max_date: '2020-09-26'
    consumption_max_power: 'true'
    consumption_price_base: '0.2276'
    consumption_price_hc: '0.1828'
    consumption_price_hp: '0.246'
    enable: 'true'
    name: Maison
    offpeak_hours_0: 12H40-14H40;1H40-7H40
    offpeak_hours_1: 12H40-14H40;1H40-7H40
    offpeak_hours_2: 12H40-14H40;1H40-7H40
    offpeak_hours_3: 12H40-14H40;1H40-7H40
    offpeak_hours_4: 12H40-14H40;1H40-7H40
    offpeak_hours_5: 12H40-14H40;1H40-7H40
    offpeak_hours_6: 12H40-14H40;1H40-7H40
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: '2021-06-01'
    production_max_date: '2021-06-01'
    production_price: '0.0'
    refresh_addresse: 'false'
    refresh_contract: 'false'
    token: ---------------
port: 5000
tempo:
  enable: true
  price_blue_hc: 0.1056
  price_blue_hp: 0.1369
  price_red_hc: 0.1328
  price_red_hp: 0.7324
  price_white_hc: 0.1246
  price_white_hp: 0.1654
```
</details>

**Type d'installation**

- [x] Docker
- [ ] HassIO

**Version : 0.9.1**

Lancement initial (pas de cache.db)
```
sudo docker-compose up -d
```

Apres lecture et validation de la config:
```
2023-09-20 08:10:30.143 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-09-20 08:10:30.143 -     INFO : Check config.yaml :
2023-09-20 08:10:30.143 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-09-20 08:10:30.143 -     INFO : CONFIG VALID
2023-09-20 08:10:30.143 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-09-20 08:10:30.161 -     INFO : Configure Databases
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: config
```
et localement:
```
HomeAutomation@HomeAutomation:~/temp/data$ ll
total 2092
drwxr-xr-x 2 root root    4096 Sep 20 06:10 ./
drwxr-xr-x 3 root root    4096 Sep 19 09:11 ../
-rw-r--r-- 1 root root       0 Sep 20 06:10 cache.db
-rw-r--r-- 1 root root    1881 Sep 19 09:14 config.yaml
```
