### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by Galadinos** [MyElectricalData/myelectricaldata_import#417]
**Description du bug**
Hello,
Tous les sensors MQTT ne remontent pas, j'ai que :
consumption
consumption.history
consumption.last5day
RTE> J0, J1 et J2

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 14400
debug: false
home_assistant:
  card_myenedis: true
  discovery_prefix: homeassistant
  enable: true
home_assistant_ws:
  enable: true
  ssl: true
  token: XXXXXXXX
  url: XXXXXX
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: XXXXXXXXX
  password: XXXXXXXXXX
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: XXXXXXXX
myelectricaldata:
  XXXXXXXXXXXXX:
    cache: true
    consumption: true
    consumption_detail: true
    consumption_detail_max_date: '2020-01-29'
    consumption_max_date: '2020-01-29'
    consumption_price_base: '0.1740'
    consumption_price_hc: '0.1470'
    consumption_price_hp: '0.1840'
    enable: true
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    production: false
    production_detail: false
    production_detail_max_date: ''
    production_max_date: ''
    production_price: 0
    refresh_addresse: true
    refresh_contract: true
    token: XXXXXX
  'XXXXXXXXXX':
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_max_power: 'true'
    consumption_price_base: '0.174'
    consumption_price_hc: '0.147'
    consumption_price_hp: '0.184'
    enable: 'true'
    name: Maison
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: ''
    production_max_date: ''
    production_price: '0'
    refresh_addresse: 'false'
    refresh_contract: 'false'
    token: XXXXXXXXX
```
</details>

**Type d'installation**

- [X] Docker

**Version : 0.9.2**
