### ISSUE TITLE
Problème d'import avec maj Enedis

### ISSUE THREAD

**Issue by Userfreedu42** [MyElectricalData/myelectricaldata_import#423]
**Description du bug**
Bonjour,
Suite à la maj d'Enedis je pense que via le passerelle, qu'il y a un bug dans la récupération des données

<details>
2023-10-11 10:26:36.066 -     INFO : [XXXXXX] RÉCUPÉRATION DE LA CONSOMMATION JOURNALIÈRE :
2023-10-11 10:26:36.066 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-10-11 10:26:36.073 -     INFO : 127.0.0.1:40568 - "GET / HTTP/1.1" 200
2023-10-11 10:26:36.099 -     INFO : Récupération des données : 2020-10-13 => 2023-10-13
2023-10-11 10:26:41.319 -     INFO : 127.0.0.1:40570 - "GET / HTTP/1.1" 200
2023-10-11 10:26:42.004 -     INFO :  Chargement des données depuis MyElectricalData 2020-10-13 => 2023-10-13
2023-10-11 10:26:42.418 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/query_daily.py", line 101, in run
    interval_reading = meter_reading["interval_reading"]
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2023-10-11 10:26:42.421 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/jobs.py", line 259, in get_consumption
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 248, in run
    Daily(headers=self.header_generate(), usage_point_id=usage_point_id).get()
  File "/app/models/query_daily.py", line 168, in get
    if "exit" in response:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-10-11 10:26:42.424 -    ERROR : Erreur lors de la récupération de la consommation journalière
2023-10-11 10:26:42.424 -    ERROR : argument of type 'NoneType' is not iterable
2023-10-11 10:26:42.424 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-10-11 10:26:42.425 -     INFO : [XXXX] RÉCUPÉRATION DE LA CONSOMMATION DÉTAILLÉE :
2023-10-11 10:26:42.425 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-10-11 10:26:42.439 -     INFO : Récupération des données : 2023-10-06 => 2023-10-13
2023-10-11 10:26:42.469 -     INFO :  - 11519m absente du relevé.
2023-10-11 10:26:42.470 -     INFO :  Chargement des données depuis MyElectricalData 2023-10-06 => 2023-10-13
2023-10-11 10:26:42.886 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/query_detail.py", line 120, in run
    for interval_reading in meter_reading["interval_reading"]:
                            ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2023-10-11 10:26:42.889 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/jobs.py", line 283, in get_consumption_detail
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 272, in run
    Detail(headers=self.header_generate(), usage_point_id=usage_point_id).get()
  File "/app/models/query_detail.py", line 200, in get
    if "exit" in response:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-10-11 10:26:42.891 -    ERROR : Erreur lors de la récupération de la consommation détaillée
2023-10-11 10:26:42.891 -    ERROR : argument of type 'NoneType' is not iterable
2023-10-11 10:26:42.892 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-10-11 10:26:42.892 -     INFO : [XXXXXX] RÉCUPÉRATION DE LA PRODUCTION JOURNALIÈRE :
2023-10-11 10:26:42.892 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-10-11 10:26:42.907 -     INFO : Récupération des données : 2023-08-30 => 2023-10-13
2023-10-11 10:26:43.136 -     INFO :  Chargement des données depuis MyElectricalData 2023-08-30 => 2023-10-13
2023-10-11 10:26:43.555 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/query_daily.py", line 101, in run
    interval_reading = meter_reading["interval_reading"]
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2023-10-11 10:26:43.557 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/jobs.py", line 310, in get_production
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 299, in run
    measure_type="production").get()
                               ^^^^^
  File "/app/models/query_daily.py", line 168, in get
    if "exit" in response:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-10-11 10:26:43.560 -    ERROR : Erreur lors de la récupération de la production journalière
2023-10-11 10:26:43.560 -    ERROR : argument of type 'NoneType' is not iterable
2023-10-11 10:26:43.561 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-10-11 10:26:43.562 -     INFO : [XXXXXX] RÉCUPÉRATION DE LA PRODUCTION DÉTAILLÉE :
2023-10-11 10:26:43.562 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2023-10-11 10:26:43.576 -     INFO : Récupération des données : 2023-10-06 => 2023-10-13
2023-10-11 10:26:43.585 -     INFO :  - 11519m absente du relevé.
2023-10-11 10:26:43.585 -     INFO :  Chargement des données depuis MyElectricalData 2023-10-06 => 2023-10-13
2023-10-11 10:26:44.009 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/query_detail.py", line 120, in run
    for interval_reading in meter_reading["interval_reading"]:
                            ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2023-10-11 10:26:44.010 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/jobs.py", line 334, in get_production_detail
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 323, in run
    Detail(headers=self.header_generate(), usage_point_id=usage_point_id, measure_type="production").get()
  File "/app/models/query_detail.py", line 200, in get
    if "exit" in response:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2023-10-11 10:26:44.012 -    ERROR : Erreur lors de la récupération de la production détaillée
2023-10-11 10:26:44.012 -    ERROR : argument of type 'NoneType' is not iterable
2023-10-11 10:26:44.012 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

```yaml
cycle: 18000
debug: true
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
home_assistant_ws:
  enable: true
  ssl: true
  token: XXXXX
  url: h0merometlaura.duckdns.org
influxdb:
  batching_options:
    batch_size: 1000
    exponential_base: 2
    flush_interval: 1000
    jitter_interval: 0
    max_retries: 5
    max_retry_delay: 125000
    max_retry_time: 180000
    retry_interval: 5000
  bucket: myelectricaldata
  enable: false
  hostname: influxdb
  method: synchronous
  org: myelectricaldata
  port: 8086
  token: XXXXX
log2file: false
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: core-mosquitto
  password: XXXX
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: mqtt
myelectricaldata:
  'XXXXX':
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: '2016-05-30'
    consumption_max_date: '2016-05-30'
    consumption_max_power: 'true'
    consumption_price_base: '0.175'
    consumption_price_hc: '0.1615'
    consumption_price_hp: '0.2228'
    enable: 'true'
    name: Maison
    offpeak_hours_0: 22H00-6H00
    offpeak_hours_1: 22H00-6H00
    offpeak_hours_2: 22H00-6H00
    offpeak_hours_3: 22H00-6H00
    offpeak_hours_4: 22H00-6H00
    offpeak_hours_5: 22H00-6H00
    offpeak_hours_6: 22H00-6H00
    plan: HC/HP
    production: 'true'
    production_detail: 'true'
    production_detail_max_date: '2023-08-30'
    production_max_date: '2023-08-30'
    production_price: '0.1339'
    refresh_addresse: 'false'
    refresh_contract: 'false'
    token: XYZ
tempo:
  enable: true
  price_blue_hc: 0.1056
  price_blue_hp: 0.1369
  price_red_hc: 0.1328
  price_red_hp: 0.7324
  price_white_hc: 0.1246
  price_white_hp: 0.1654
wipe_influxdb: false

```
</details>

**Type d'installation**
- [ ] HassIO

**Version : 0.9.2**
