### ISSUE TITLE
[BUG] - MQTTS avec SelfSigned certificate

### ISSUE THREAD

**Issue by sbourdette** [MyElectricalData/myelectricaldata_import#454]
**Description du bug**
J'ai configuré un container docker MQTT pour écouter en MQTTS (Port 883 avec certificats autosignés)
Dans la configuration de Myelectrical_import, on ne peut pas fournir de certificat d'autorité afin de valider le certificat auto-signé

Le connexion à mqtt en mqtts est impossible.

<details>

Dans Home Assistant, on a la possibilité d'uploader un ca file (cf capture)

<summary>Configuration (config.yaml)</summary>

```yaml
mqtt:
  enable: true
  hostname: mqtt.local
  port: 8883
  username: null
  password: null
  prefix: myelectricaldata
  client_id: myelectricaldata     # DOIT ETRE UNIQUE SUR LA TOTALITE DES CLIENTS CONNECTE AU SERVEUR MQTT
  retain: true
  qos: 0```
</details>

**Type d'installation**

- [X ] Docker
- [ ] HassIO

**Version : 0.9.3**

![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/5262926/2e194b06-1030-4505-bd7e-372b823b71ae)

**Comment by sbourdette** [comment]
![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/5262926/0a57a3ff-6b54-45a7-b24e-69b65b04aad9)

**Comment by koukihai** [comment]
Bonjour!
J'ai tente d'implementer cette fonctionnalite dans la PR#461.
Si tu souhaites la tester, j'ai construit une image basee sur `master`

**Avertissement**: Je ne peux pas t'assurer que toutes les fonctionnalites soient operationnelles car j'utilise master comme base, et pas une release de production. Je te conseille de faire un backup de ta db si tu decides de deployer cette image.

<details><summary>J'ai lu l'avertissement</summary>

Voici l'image: `ghcr.io/koukihai/myelectricaldata_import:issue-454`

Construite a partir de l'action suivante: https://github.com/koukihai/myelectricaldata_import/actions/runs/7467642253/job/20321540005
</details>

**Comment by m4dm4rtig4n** [comment]
@sbourdette a tu pu essayer la fonctionnalité ? 
Elle est dispo dans la 0.11.0-RC

**Comment by sbourdette** [comment]
> @sbourdette a tu pu essayer la fonctionnalité ? Elle est dispo dans la 0.11.0-RC ou 0.11.0-RC

Salut, désolé, je suis débordé en ce moment et je n'ai pas pu testé encore.

**Comment by sbourdette** [comment]
Bonsoir,
Je viens de faire un test. myelectrical essaye à priori de se connecter en TLSV1
J'ai ca comme message d'erreur dans les log mosquitto : 

`Client connection from 172.22.0.3 failed: error:1402542E:SSL routines:ACCEPT_SR_CLNT_HELLO:tlsv1 alert protocol version.`

Dans la conf mosquitto j'ai essayé de descendre le niveau de TLS :
`tls_version tlsv1.1`

Ma conf mqtt: 
```

mqtt:
  enable: true
  hostname: mqttrc.xxxxx.int
  port: 8884
  username: null
  password: null
  prefix: myelectricaldata
  client_id: myelectricaldata     # DOIT ETRE UNIQUE SUR LA TOTALITE DES CLIENTS CONNECTE AU SERVEUR MQTT
  retain: true
  qos: 0
  ca_cert: "/etc/ssl/ca_xxxxx.int.crt"
# Configuration SSL optionnel.
ssl:
  certfile: "/etc/ssl/wildcard_xxxxx.int.crt"
  keyfile: "/etc/ssl/wildcard_xxxxx.int.key"

```

Le log myelectrical : 

```
2024-02-08 23:34:20.269 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-08 23:34:20.270 -     INFO : [22435745161674] GÉNÉRATION DES STATISTIQUES TARIFAIRE DE CONSOMMATION/PRODUCTION  :
2024-02-08 23:34:20.270 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-08 23:34:20.270 -     INFO : Consommation :
2024-02-08 23:34:20.296 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ TERMINE ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-08 23:34:20.297 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-08 23:34:20.297 -     INFO : [22435745161674] EXPORT MQTT
2024-02-08 23:34:20.297 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-08 23:34:20.298 -     INFO : Statut du compte.


```

Je ne sais pas ce que je peux faire de pluls comme vérification
