### ISSUE TITLE
[BUG] - Ratio HP / HC

### ISSUE THREAD

**Issue by loicdelecroix** [MyElectricalData/myelectricaldata_import#471]
Hello,

Tout d'abord, merci pour cette app, hyper complète et vachement utile quand on a pas de Linkee ! :)

**Description du bug**
Je constate un petit bug sur le calcul du pourcentage HP / HC chez moi, qui me met une valeur ultra faible (~0) malgré les bonnes données "bruts" sur les valeurs HP et HC.

Petit extrait des données que je récupère dans HA : 
![bug_1](https://github.com/MyElectricalData/myelectricaldata_import/assets/45817385/e9e6f769-f328-47e5-91f0-7316c75cfe98)
![bug_2](https://github.com/MyElectricalData/myelectricaldata_import/assets/45817385/5da85129-beb5-493b-b9c8-12820026d335)

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
port: 5000
debug: true
log2file: false
tempo:
  enable: false
influxdb:
  enable: false
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: homeassistant
home_assistant_ws:
  enable: true
  ssl: false
  token: XXXXXXXXX
  url: "XXXXXXX"
mqtt:
  enable: true
  hostname: core-mosquitto
  port: 1883
  username: XXXXXX
  password: XXXXXX
  prefix: myelectricaldata
  client_id: myelectricaldata
  retain: true
  qos: 0
myelectricaldata:
  "XXXXXXXXXX":
    enable: "true"
    token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    name: XXXXXXXX
    addresses: "false"
    cache: "true"
    consumption: "true"
    consumption_detail: "true"
    consumption_price_base: "0.2276"
    consumption_price_hc: "0.1828"
    consumption_price_hp: "0.2460"
    offpeak_hours_0: 1H00-7H00;12H30-14H30
    offpeak_hours_1: 1H00-7H00;12H30-14H30
    offpeak_hours_2: 1H00-7H00;12H30-14H30
    offpeak_hours_3: 1H00-7H00;12H30-14H30
    offpeak_hours_4: 1H00-7H00;12H30-14H30
    offpeak_hours_5: 1H00-7H00;12H30-14H30
    offpeak_hours_6: 1H00-7H00;12H30-14H30
    plan: HC/HP
    production: "false"
    production_detail: "false"
    production_price: "0.0"
    production_max_date: "2021-06-01"
    production_detail_max_date: "2021-06-01"
    refresh_addresse: "false"
    refresh_contract: "false"
```
</details>

**Type d'installation**

- [ ] Docker
- [X] HassIO

**Version : 0.9.3**

Dispo si besoin pour plus de détails
