### ISSUE TITLE
[BUG] - Changement dans le calcul des HC / HP ?

### ISSUE THREAD

**Issue by loicdelecroix** [MyElectricalData/myelectricaldata_import#491]
**Description du bug**
Hello,

Depuis la 0.10.0 installée ce matin, je constate des décalages entre les HC/HP calculées par le add-on, et celles présentes chez EDF / Jeedom.
Pour le contexte, je migre de Jeedom à HA en ce moment, et j'utilisais précédemment le plugin Enedis de Jeedom, combiné à un script en PHP pour le calcul des HC / HP.

Jusqu'à hier, les données calculées coté Jeedom & par MyElectricalData étaient les mêmes que celles présentes coté EDF.
Mais depuis ce matin et le passage à la 0.10.0, j'ai des décalages entre les valeurs.
Ce décalage ne concerne que les HC / HP, la consommation journalière totale est correcte.

Exemple sur la journée du mardi 06/02 : 
**EDF**
![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/45817385/c49082e5-8e6a-49e5-a292-a709e0bf8e34)

**Jeedom**
HP : 
![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/45817385/bbf9d2b5-5a21-4adb-a878-a5e553c87b13)
HC : 
![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/45817385/39d4ec38-6140-4f60-89ca-05bea50e5041)

**HA**
![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/45817385/96ee29f3-faa4-43fc-904a-c9abe4b09420)

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
port: 5000
debug: true
log2file: false
tempo:
  enable: false
influxdb:
  enable: false
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: homeassistant
home_assistant_ws:
  enable: true
  ssl: false
  token: XXXXXXXXX
  url: "XXXXXXX"
mqtt:
  enable: true
  hostname: core-mosquitto
  port: 1883
  username: XXXXXX
  password: XXXXXX
  prefix: myelectricaldata
  client_id: myelectricaldata
  retain: true
  qos: 0
myelectricaldata:
  "XXXXXXXXXX":
    enable: "true"
    token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    name: XXXXXXXX
    addresses: "false"
    cache: "true"
    consumption: "true"
    consumption_detail: "true"
    consumption_price_base: "0.2276"
    consumption_price_hc: "0.1828"
    consumption_price_hp: "0.2460"
    offpeak_hours_0: 1H00-7H00;12H30-14H30
    offpeak_hours_1: 1H00-7H00;12H30-14H30
    offpeak_hours_2: 1H00-7H00;12H30-14H30
    offpeak_hours_3: 1H00-7H00;12H30-14H30
    offpeak_hours_4: 1H00-7H00;12H30-14H30
    offpeak_hours_5: 1H00-7H00;12H30-14H30
    offpeak_hours_6: 1H00-7H00;12H30-14H30
    plan: HC/HP
    production: "false"
    production_detail: "false"
    production_price: "0.0"
    production_max_date: "2021-06-01"
    production_detail_max_date: "2021-06-01"
    refresh_addresse: "false"
    refresh_contract: "false"
```
</details>

**Type d'installation**

- [ ] Docker
- [X] HassIO

**Version : 0.10.0**

Dispo si besoin d'autres infos; et encore merci pour ce projet, qui aide vachement la communauté !
