### ISSUE TITLE
[BUG] - Pb acces dashboard post maj version 0.10.0

### ISSUE THREAD

**Issue by therealcorwin** [MyElectricalData/myelectricaldata_import#493]
Hello,

Après la mise à jour vers la version 0.10.0, il m'est impossible d'aller sur mon dashboard de consommation de mon PDL (après la sélection de mon pdl)

J'ai l'erreur suivante (et un ecran noir sur HA) :

`2024-02-10 19:22:26.815 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-10 19:22:26.815 -     INFO : REFRESH ORM OBJECTS
2024-02-10 19:22:26.815 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-02-10 19:22:26.934 -     INFO : 172.30.32.1:0 - "GET /usage_point_id/21435455822802 HTTP/1.1" 500
[10/Feb/2024:19:22:26 +0100] 500 192.168.1.80, 172.30.32.1(172.30.32.2) GET /usage_point_id/21435455822802 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0)
2024-02-10 19:22:26.934 -    ERROR : Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/fastapi/routing.py", line 193, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/starlette/concurrency.py", line 40, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/routers/html.py", line 26, in usage_point_id
    return UsagePoint(usage_point_id).display()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/usage_point.py", line 305, in display
    datatable = str(self.get_price("consumption"))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/usage_point.py", line 907, in get_price
    html += generate_price_compare(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/templates/usage_point.py", line 857, in generate_price_compare
    evolution_2 = round(data["price_3"] - data["price_1"], 2)
                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'
2024-02-10 19:22:30.252 -     INFO : 127.0.0.1:56956 - "GET / HTTP/1.1" 200`

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 14400 # 4H
debug: true
log2file: false
wipe_influxdb: false # Work only with influxdb > 2.X
tempo:
  enable: false
  price_blue_hc: 0.097
  price_blue_hp: 0.1249
  price_red_hc: 0.1216
  price_red_hp: 0.6712
  price_white_hc: 0.114
  price_white_hp: 0.1508
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: homeassistant
home_assistant_ws: # FOR ENERGY TAB
  enable: true
  ssl: false
  token: "XXXXXXXXX"
  url: XXXXXXXXX:8123
influxdb:
  enable: true
  hostname: XXXXXX-influxdb
  port: 8086
  token: XXXXXXXXX
  bucket: "myelectricaldata/autogen"
  org: "-"
  method: synchronous # Mode disponible : synchronous / asynchronous / batching
  batching_options:
    batch_size: 1000
    flush_interval: 1000
    jitter_interval: 0
    retry_interval: 5000
    max_retry_time: 180_000
    max_retries: 5
    max_retry_delay: 125_000
    exponential_base: 2
mqtt:
  enable: true
  hostname: XXXXXXX
  port: 18830
  username: XXXXX
  password: XXXXXX
  prefix: myelectricaldata
  client_id: myelectricaldata # DOIT ETRE UNIQUE SUR LA TOTALITE DES CLIENTS CONNECTE AU SERVEUR MQTT
  retain: true
  qos: 0
myelectricaldata:
  "XXXXXXXXXXX":
    enable: "true"
    token: XXXXXXXXXXX
    name: "Maison"
    addresses: "true"
    cache: "true"
    consumption: "true"
    consumption_detail: "true"
    consumption_price_base: "0.2516"
    consumption_price_hc: "0.2068"
    consumption_price_hp: "0.2700"
    consumption_max_date: "2021-06-01"
    consumption_detail_max_date: "2021-06-01"
    offpeak_hours_0: 21H54-5H54 # LUNDI
    offpeak_hours_1: 21H54-5H54 # MARDI
    offpeak_hours_2: 21H54-5H54 # MERCREDI
    offpeak_hours_3: 21H54-5H54 # JEUDI
    offpeak_hours_4: 21H54-5H54 # VENDREDI
    offpeak_hours_5: 21H54-5H54 # SAMEDI
    offpeak_hours_6: 21H54-5H54 # DIMANCHE
    plan: HC/HP
    production: "false"
    production_detail: "false"
    production_price: "0.0"
    production_max_date: "2021-06-01"
    production_detail_max_date: "2021-06-01"
    refresh_addresse: "false"
    refresh_contract: "false"

```
</details>

**Type d'installation**

- [ ] Docker
- [X] HassIO

**Version : 0.10.0**
