### ISSUE TITLE
[BUG] - Absence de tag HP ou HC dans les consos détaillées dans influxDB

### ISSUE THREAD

**Issue by nonobzh29** [MyElectricalData/myelectricaldata_import#494]
**Description du bug**
Depuis l'installation de la 0.10.0 (faite le 5/02 au matin), les données de conso détaillées (consumption_detail) dans InfluxDB n'ont plus de tag HP ou HC.
<img width="1100" alt="Capture d’écran 2024-02-11 à 18 40 22" src="https://github.com/MyElectricalData/myelectricaldata_import/assets/17364399/ef8ff601-b507-4011-aa3b-fee788d5fa9a">

Dans le dashboard Grafana ça a pour conséquence de ne plus afficher les données détaillées.
<img width="1187" alt="Capture d’écran 2024-02-11 à 18 39 55" src="https://github.com/MyElectricalData/myelectricaldata_import/assets/17364399/c9958e37-c902-4a06-a584-7b29eb1706b9">

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 14400
debug: true
home_assistant:
  discovery_prefix: homeassistant
  enable: false
home_assistant_ws:
  enable: false
  ssl: true
  token: HOME_ASSISTANT_TOKEN_GENERATE_IN_PROFILE_TABS_(BOTTOM)
  url: ha.test.com
influxdb:
  bucket: myelectricaldata/autogen
  enable: true
  hostname: influxdb
  method: asynchronous
  org: '-'
  port: 8086
  timezone: Europe/Paris
  token: ''
log2file: false
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: mosquitto
  password: xxxxxxx
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: xxxxxxxx
myelectricaldata:
  'xxxxxxxxxxxxxxx':
    addresses: true
    cache: true
    consumption: true
    consumption_detail: true
    consumption_detail_max_date: '2020-01-01'
    consumption_max_date: '2020-01-01'
    consumption_price_base: '0.2122'
    consumption_price_hc: '0.1727'
    consumption_price_hp: '0.2284'
    enable: true
    name: Maison
    offpeak_hours_0: 0H50-6H50;19H50-21H50
    offpeak_hours_1: 0H50-6H50;19H50-21H50
    offpeak_hours_2: 0H50-6H50;19H50-21H50
    offpeak_hours_3: 0H50-6H50;19H50-21H50
    offpeak_hours_4: 0H50-6H50;19H50-21H50
    offpeak_hours_5: 0H50-6H50;19H50-21H50
    offpeak_hours_6: 0H50-6H50;19H50-21H50
    plan: BASE
    production: false
    production_detail: false
    production_detail_max_date: ''
    production_max_date: ''
    production_price: '0.0'
    refresh_addresse: false
    refresh_contract: false
    token: xxxxxxxxxxxxxxxxxxxxxx
tempo:
  enable: true
wipe_cache: false
wipe_influxdb: false
```
</details>

**Type d'installation**

- [X] Docker
- [ ] HassIO

**Version : 0.10.0**
