### ISSUE TITLE
[BUG] - MQTT sensors indisponibilité régulière

### ISSUE THREAD

**Issue by Ken-dono** [MyElectricalData/myelectricaldata_import#513]
**Description du bug**

Les sensors MQTT mis à disposition "clignotent" indisponible. La remontée de donnée est bien effectuée mais, à rythme régulier, les sensors deviennent indisponibles. Cela semble empêcher l'ajout au Dashboard Energy.

![image](https://github.com/MyElectricalData/myelectricaldata_import/assets/63581309/68438cbd-37be-4726-8549-8790e3833e2c)

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 14400
debug: true
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
log2file: true
mqtt:
  enable: true
  hostname: core-mosquitto
  port: 1883
  username: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  password: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  prefix: myelectricaldata
  client_id: mqtt_user # DOIT ETRE UNIQUE SUR LA TOTALITE DES CLIENTS CONNECTE AU SERVEUR MQTT
  retain: true
  qos: 0
myelectricaldata:
  XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:
    addresses: "false"
    cache: "true"
    consumption: "true"
    consumption_detail: "true"
    consumption_detail_max_date: ""
    consumption_max_date: ""
    consumption_max_power: "true"
    consumption_price_base: "0.145907"
    consumption_price_hc: "0.124364"
    consumption_price_hp: "0.164915"
    enable: "true"
    name: Appart ANGERS
    offpeak_hours_0: 22H00-6H00
    offpeak_hours_1: 22H00-6H00
    offpeak_hours_2: 22H00-6H00
    offpeak_hours_3: 22H00-6H00
    offpeak_hours_4: 22H00-6H00
    offpeak_hours_5: 22H00-6H00;12H00-14H00
    offpeak_hours_6: 22H00-6H00;12H00-14H00
    plan: HC/HP
    production: "false"
    production_detail: "false"
    production_detail_max_date: ""
    production_max_date: ""
    production_price: "0.0"
    refresh_addresse: "false"
    refresh_contract: "true"
    token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
tempo:
  enable: false
  price_blue_hc: 0.097
  price_blue_hp: 0.1249
  price_red_hc: 0.1216
  price_red_hp: 0.6712
  price_white_hc: 0.114
  price_white_hp: 0.1508
wipe_influxdb: false
```
</details>

**Type d'installation**

- [ ] Docker
- [X] HassIO

**Version : 0.12.0**
