### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by LoicHarrang** [MyElectricalData/myelectricaldata_import#520]
**Description du bug**
Lors de l'import des données depuis Enedis, les consommations se reporte bien, seul les informations du contrat et les informations postales ne sont pas récupéré. Voici l'erreur pour les 2 : 

2024-04-03 09:20:39.029 -     INFO : [MonNumeroPDLQueJeCache] RÉCUPÉRATION DES INFORMATIONS CONTRACTUELLES :
2024-04-03 09:20:39.029 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-04-03 09:20:39.047 -     INFO :  =>  Pas de cache
2024-04-03 09:20:40.024 -    ERROR : {'error': True, 'description': 'No consent can be found for this customer and this usage point.'}

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 14400
debug: true
home_assistant:
  card_myenedis: true
  discovery_prefix: homeassistant
  enable: true
influxdb:
  batching_options:
    batch_size: 1000
    exponential_base: 2
    flush_interval: 1000
    jitter_interval: 0
    max_retries: 5
    max_retry_delay: 125000
    max_retry_time: 180000
    retry_interval: 5000
  bucket: enedis/autogen
  enable: true
  hostname: a0d7b954-influxdb
  method: synchronous
  org: "-"
  port: 8086
  scheme: http
  token: UserEtMotDePasseBDDQueJeCache
log2file: true
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: core-mosquitto
  password: mqtt
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: mqtt
myelectricaldata:
  "MonPDLQueJeCache":
    cache: "true"
    consumption: "true"
    consumption_detail: "true"
    consumption_detail_max_date: ""
    consumption_max_date: ""
    consumption_max_power: "true"
    consumption_price_base: "0.1415"
    consumption_price_hc: "0.0984"
    consumption_price_hp: "0.1315"
    enable: "true"
    name: Appartement
    offpeak_hours_0: 22H00-06H00
    offpeak_hours_1: 22H00-06H00
    offpeak_hours_2: 22H00-06H00
    offpeak_hours_3: 22H00-06H00
    offpeak_hours_4: 22H00-06H00
    offpeak_hours_5: 22H00-06H00
    offpeak_hours_6: 22H00-06H00
    plan: Tempo
    production: "true"
    production_detail: "true"
    production_detail_max_date: ""
    production_max_date: ""
    production_price: "0.0"
    refresh_addresse: "true"
    refresh_contract: "true"
    token: MonTokenQueJeCache

```
</details>

**Type d'installation**

- [x] HassIO

**Version : 2024.3.3**
