### ISSUE TITLE
[BUG] - Prix dans l'ntégration par mqtt qui sont arrondis à 1 chiffre parès la virgule (?)

### ISSUE THREAD

**Issue by r-jean-pierre** [MyElectricalData/myelectricaldata_import#525]
**Description du bug**
Bonjour,

Si l'on passe par mqtt pour avoir des sensors dans HA, dans celui qui donne tous les attributs,
j'ai `yesterday_HP_cost`, `dailyweek_costHC`, etc. qui sont tous à 1 seul chiffre après la virgule.
Je sais pas si c'est voulu, mais à la journée, surtout en HC, je n'aurais pas été contre 3 chiffres après la virgule, en mode prix de l'essence (ou bien même 4, c'est plus facile d’arrondir dans ses cards que refaire les calculs).

Voici ce que j'ai:

![2024-04-25 23_11_28-Settings – Home Assistant](https://github.com/MyElectricalData/myelectricaldata_import/assets/9727894/6e5500db-97bb-47f2-b517-6f4382b6eced)

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
myelectricaldata:
  *:
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: '2021-06-01'
    consumption_max_date: '2021-06-01'
    consumption_max_power: 'true'
    consumption_price_base: 0.2795
    consumption_price_hc: 0.1927
    consumption_price_hp: 0.2795
    enable: 'true'
    name: Maison
    offpeak_hours_0: 22H00-6H00
    offpeak_hours_1: 22H00-6H00
    offpeak_hours_2: 22H00-6H00
    offpeak_hours_3: 22H00-6H00
    offpeak_hours_4: 22H00-6H00
    offpeak_hours_5: 22H00-6H00
    offpeak_hours_6: 22H00-6H00
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: '2021-06-01'
    production_max_date: '2021-06-01'
    production_price: '0.0'
    refresh_addresse: 'true'
    refresh_contract: 'true'
```
</details>
Vous remarquerez dans ma config que j'ai bien renseigné mes prix HP/HC avec 4 chiffres après la virgule
<br />
<br />

**Type d'installation**

- [x] Docker
- [ ] HassIO

**Version : 1.12.0**
