### ISSUE TITLE
[BUG] - pas de mise à jour du contrat

### ISSUE THREAD

**Issue by Gandulf78** [MyElectricalData/myelectricaldata_import#526]
**Description du bug**
J'ai changé il y a 4 j mon contrat EDF pour changer la puissance souscrite (passage de 9kVA à 6kVA). Je vois bien la nouvelle puissance sur enedis.fr. 
Myelectricaldata ne s'est pas mis à jour automatiquement malgré un forçage du redémarrage du container. 
J'ai aussi essayé de modifier la valeur 
Refreshcontract en la mettant à true. 
J'obtiens dans les logs:

```
2024-04-27 14:45:26.853 -     INFO : [xxx] RÉCUPÉRATION DES INFORMATIONS CONTRACTUELLES :
2024-04-27 14:45:26.853 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-04-27 14:45:26.858 -     INFO :  =>  Mise à jour du cache
2024-04-27 14:45:28.350 -    ERROR : {'error': True, 'description': 'No consent can be found for this customer and this usage point.'}
```

J'ai tenté de renouveler le consentement mais ça n'a rien changé. 
A part cela les données sont bien récupérées. 
Semble lié à https://github.com/MyElectricalData/myelectricaldata_import/issues/516

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
RENSEIGNE TON FICHIER DE CONFIG SANS PDL & TOKEN

cycle: 14400  # 4H
debug: false
log2file: false
wipe_influxdb: false
tempo:
  enable: false
  price_blue_hc: 0.1296
  price_blue_hp: 0.1609
  price_red_hc: 0.1568
  price_red_hp: 0.7562
  price_white_hc: 0.1486
  price_white_hp: 0.1894
home_assistant:
  enable: true
  discovery: true
  discovery_prefix: homeassistant
home_assistant_ws:
  enable: true
  ssl: true
  purge: false
  token: ***
  url: myelectricaldata.mydomain.fr
influxdb:
  enable: true
  hostname: influxdb
  port: 8086
  token: ***
  org: Personal
  bucket: myelectricaldata
  method: batching
  batching_options:
    batch_size: 1000
    flush_interval: 1000
    jitter_interval: 0
    retry_interval: 5000
    max_retry_time: 180_000
    max_retries: 5
    max_retry_delay: 125_000
    exponential_base: 2
mqtt:
  enable: true
  hostname: host.docker.internal
  port: 1883
  username: user
  password: password
  prefix: myelectricaldata
  client_id: myelectricaldata
  retain: true
  qos: 0

myelectricaldata:
  "xxx":
    enable: 'true'
    token: ***
    name: "Maison"
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_base: '0.2516'
    consumption_price_hc: "0.1704"
    consumption_price_hp: "0.27"
    consumption_max_date: "2022-04-01"
    consumption_detail_max_date: "2022-04-01"
    offpeak_hours_0: 20H00-8H00;13H00-18H00   # LUNDI
    offpeak_hours_1: 20H00-8H00;13H00-18H00   # MARDI
    offpeak_hours_2: 20H00-8H00;13H00-18H00   # MERCREDI
    offpeak_hours_3: 20H00-8H00;13H00-18H00   # JEUDI
    offpeak_hours_4: 20H00-8H00;13H00-18H00   # VENDREDI
    offpeak_hours_5: 20H00-8H00;13H00-18H00   # SAMEDI
    offpeak_hours_6: 20H00-8H00;13H00-18H00   # DIMANCHE
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_price: '0.0'
    production_max_date: "2022-04-01"
    production_detail_max_date: "2022-04-01"
    refresh_addresse: 'false'
    refresh_contract: 'false'

```
</details>

**Type d'installation**

- [X] Docker
- [ ] HassIO

**Version : 0.13.0-rc.4**
