### ISSUE TITLE
[BUG] - Pas de endpoint pour les données de puissance

### ISSUE THREAD

**Issue by codavs65r** [MyElectricalData/myelectricaldata_import#529]
**Description du bug**
Les endpoints pour les données de puissance ne sont pas référencés dans le swagger sur mon installation.

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 14400
debug: true
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
home_assistant_ws: # FOR ENERGY TAB
  enable: true
  ssl: true
  token: "--"
  url: ha.noisyspoon.net
  max_date: "2022-05-01"
  purge: false
influxdb:
  batching_options:
    batch_size: 1000
    exponential_base: 2
    flush_interval: 1000
    jitter_interval: 0
    max_retries: 5
    max_retry_delay: 125000
    max_retry_time: 180000
    retry_interval: 5000
  bucket: myelectricaldata
  enable: false
  hostname: influxdb
  method: synchronous
  org: myelectricaldata
  port: 8086
  token: myelectricaldata
log2file: false
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: core-mosquitto
  password: led0zep1
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: nicolas
myelectricaldata:
  '--:
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_max_power: 'true'
    consumption_price_base: '0.2347'
    consumption_price_hc: '0.175'
    consumption_price_hp: '0.175'
    enable: 'true'
    name: Linky
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: ''
    production_max_date: ''
    production_price: '0.0'
    refresh_addresse: 'false'
    refresh_contract: 'false'
    token: --
tempo:
  enable: true
  price_blue_hc: 0.097
  price_blue_hp: 0.1249
  price_red_hc: 0.1216
  price_red_hp: 0.6712
  price_white_hc: 0.114
  price_white_hp: 0.1508
wipe_influxdb: false


```
</details>

**Type d'installation**

- [ ] Docker
- [X] HassIO

**Version : 0.12.0**
