### ISSUE TITLE
[BUG] - Import des données vers Home Assistant Energy incomplète

### ISSUE THREAD

**Issue by codavs65r** [MyElectricalData/myelectricaldata_import#536]
Depuis, la mise à jour 0.13.0, les données importés dans Home Assistant Energy n'est pas complète. L'import s'arrète au 27/04/2024 à 8h.

Est-ce normal ?
Merci.

Ci-dessous le log

2024-05-25 07:57:59.991 -     INFO : Envoi des données de conso BASE vers Home Assistant 17/17 (2024-03-15T17:00:00+01:00 => 2024-04-27T08:00:00+02:00)
{'consumption': True, 'consumption_detail': True, 'production': False, 'production_detail': False, 'consumption_price_base': 0.2347, 'consumption_price_hp': 0.0, 'consumption_price_hc': 0.0, 'production_price': 0.0, 'discovery_prefix': 'homeassistant', 'activation_date': None, 'subscribed_power': '9', 'consumption_max_power': True, 'offpeak_hours_0': None, 'offpeak_hours_1': None, 'offpeak_hours_2': None, 'offpeak_hours_3': None, 'offpeak_hours_4': None, 'offpeak_hours_5': None, 'offpeak_hours_6': None}
2024-05-25 07:58:00.008 -     INFO : - sensor.linky_xxxxxxxxxx_base_consumption
2024-05-25 07:58:00.010 -     INFO : Envoi des données de coût BASE vers Home Assistant 1/17 (2022-05-17T00:00:00+02:00 => 2022-06-27T15:00:00+02:00)
<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 14400
debug: true
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
home_assistant_ws:
  enable: true
  max_date: '2022-05-01'
  purge: false
  ssl: true
  token: ???
  url: ha.noisyspoon.net
influxdb:
  batching_options:
    batch_size: 1000
    exponential_base: 2
    flush_interval: 1000
    jitter_interval: 0
    max_retries: 5
    max_retry_delay: 125000
    max_retry_time: 180000
    retry_interval: 5000
  bucket: myelectricaldata
  enable: false
  hostname: influxdb
  method: synchronous
  org: myelectricaldata
  port: 8086
  token: myelectricaldata
log2file: false
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: core-mosquitto
  password: led0zep1
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: nicolas
myelectricaldata:
  '???':
    cache: true
    consumption: true
    consumption_detail: true
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_max_power: true
    consumption_price_base: 0.2347
    consumption_price_hc: 0.0
    consumption_price_hp: 0.0
    enable: true
    name: Linky
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    production: false
    production_detail: false
    production_detail_max_date: ''
    production_max_date: ''
    production_price: 0.0
    refresh_addresse: true
    refresh_contract: true
    token: ???
tempo:
  enable: true
  price_blue_hc: 0.097
  price_blue_hp: 0.1249
  price_red_hc: 0.1216
  price_red_hp: 0.6712
  price_white_hc: 0.114
  price_white_hp: 0.1508
wipe_influxdb: false
```
</details>

**Type d'installation**

- [ ] Docker
- [X] HassIO

**Version : 0.13.0**
