### ISSUE TITLE
[BUG] - Plus de Dashboard Energie en version 0.13.0

### ISSUE THREAD

**Issue by Guizmos** [MyElectricalData/myelectricaldata_import#537]
**Description du bug**
Depuis l'update en version 0.13.0, je n'ai aucune remontée sur le Dashboard Energie Home Assistant. Aucun problème avec la version 0.12.0

<details>
<summary>Configuration (config.yaml)</summary>

```yaml

port: 5000
log2file: false
wipe_influxdb: false
cycle: 14400
debug: false
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true

influxdb:
  asynchronous: false
  bucket: myelectricaldata
  enable: false
  host: influxdb
  org: myelectricaldata
  port: 8086
  token: XXXXXXXXXXX

home_assistant_ws: # FOR ENERGY TAB
  enable: true
  ssl: true
  token: xxx
  url: xxx
  max_date: "2022-01-01"
  purge: false

mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: core-mosquitto
  password: xxx
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: xxx

myelectricaldata:
  "xxx":
    activation_date_daily: ''
    activation_date_detail: ''
    enable: 'true'
    cache: 'true'
    token: "xxx"
    name: "Maison"
    addresses: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: "2021-01-21"
    consumption_max_date: "2021-01-21"
    consumption_price_base: '0.11002'
    consumption_price_hc: 0
    consumption_price_hp: 0
    offpeak_hours_0: ""
    offpeak_hours_1: ""
    offpeak_hours_2: ""
    offpeak_hours_3: ""
    offpeak_hours_4: ""
    offpeak_hours_5: ""
    offpeak_hours_6: ""
    plan: BASE
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: "2021-01-01"
    production_max_date: "2021-01-01"
    production_price: 0
    refresh_addresse: 'false'
    refresh_contract: 'false'

```
</details>

**Type d'installation**

- [ ] Docker
- [x] HassIO

**Version : 
Core
2024.5.5
Supervisor
2024.05.1
Operating System
12.3
Interface utilisateur
20240501.1**
