### ISSUE TITLE
[BUG] - calcul des couts journalier

### ISSUE THREAD

**Issue by ben33880** [MyElectricalData/myelectricaldata_import#538]
**Description du bug**
Bonjour,
Le calcul des tarifs me semble erroné par exemple pour le dimanche en tarif bleu tempo : 1.7*0.1296 ne donne pas 0.4€

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
debug: true
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
home_assistant_ws:
  enable: true
  max_date: "2021-06-01"
  purge: false
  ssl: false
  token: 
  url: xxxxx:8123
influxdb:
  batching_options:
    batch_size: 1000
    exponential_base: 2
    flush_interval: 1000
    jitter_interval: 0
    max_retries: 5
    max_retry_delay: 125000
    max_retry_time: 180000
    retry_interval: 5000
  bucket: myelectricaldata
  enable: false
  hostname: influxdb
  method: synchronous
  org: myelectricaldata
  port: 8086
  scheme: http
  token: myelectricaldata
log2file: false
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: 192.168.XX.XX
  password: XXXXX
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: mqtt
myelectricaldata:
  "xxxxx":
    addresses: "true"
    cache: "true"
    consumption: "true"
    consumption_detail: "true"
    consumption_detail_max_date: "2021-06-01"
    consumption_max_date: "2021-06-01"
    consumption_max_power: "true"
    consumption_price_base: "0.2516"
    consumption_price_hc: "0.2068"
    consumption_price_hp: "0.27"
    enable: "true"
    name: Maison
    offpeak_hours_0: 22H00-6H00
    offpeak_hours_1: 22H00-6H00
    offpeak_hours_2: 22H00-6H00
    offpeak_hours_3: 22H00-6H00
    offpeak_hours_4: 22H00-6H00
    offpeak_hours_5: 22H00-6H00
    offpeak_hours_6: 22H00-6H00
    plan: Tempo
    production: "false"
    production_detail: "false"
    production_detail_max_date: "2021-06-01"
    production_max_date: "2021-06-01"
    production_price: "0.0"
    refresh_addresse: "true"
    refresh_contract: "true"
    token: xxxxxxx
port: 5000
ssl:
  certfile: ""
  gateway: true
  keyfile: ""
wipe_influxdb: false

```
</details>

**Type d'installation**

- [ ] Docker
- [x] HassIO

**Version : 0.13.0**
![334082333-cc3dae96-1576-41a7-876d-f686b014e125](https://github.com/MyElectricalData/myelectricaldata_import/assets/14923772/8a0d9f5f-1953-4313-9949-a81b64bae0dc)
