### ISSUE TITLE
[BUG] - Erreurs lors de la récupération des donées

### ISSUE THREAD

**Issue by codavs65r** [MyElectricalData/myelectricaldata_import#552]
**Description du bug**
Depuis le 3/07 j'ai c'es erreurs dans le log lors de la récuparétion des données.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-07-03 13:23:15.501 -     INFO : [--] RÉCUPÉRATION DE LA CONSOMMATION JOURNALIÈRE :
2024-07-03 13:23:15.501 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-07-03 13:23:15.504 -     INFO : Récupération des données : 2024-05-15 => 2024-07-05
2024-07-03 13:23:15.565 -     INFO :  Chargement des données depuis MyElectricalData 2024-05-15 => 2024-07-05
2024-07-03 13:23:16.049 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/query_daily.py", line 154, in run
    interval_reading = meter_reading["interval_reading"]
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-07-03 13:23:16.050 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/jobs.py", line 256, in get_consumption
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 245, in run
    Daily(headers=self.header_generate(), usage_point_id=usage_point_id).get()
  File "/app/models/query_daily.py", line 244, in get
    if "exit" in response:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2024-07-03 13:23:16.051 -    ERROR : Erreur lors de la récupération de la consommation journalière
2024-07-03 13:23:16.051 -    ERROR : argument of type 'NoneType' is not iterable
2024-07-03 13:23:16.052 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-07-03 13:23:16.052 -     INFO : [--] RÉCUPÉRATION DE LA CONSOMMATION DÉTAILLÉE :
2024-07-03 13:23:16.052 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-07-03 13:23:16.064 -     INFO : Récupération des données : 2024-06-28 => 2024-07-05
2024-07-03 13:23:16.098 -     INFO :  - 5759m absente du relevé.
2024-07-03 13:23:16.098 -     INFO :  Chargement des données depuis MyElectricalData 2024-06-28 => 2024-07-05
2024-07-03 13:23:16.556 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/query_detail.py", line 117, in run
    for interval_reading in meter_reading["interval_reading"]:
                            ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-07-03 13:23:16.556 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/jobs.py", line 280, in get_consumption_detail
    run(self.usage_point_config)
  File "/app/models/jobs.py", line 269, in run
    Detail(headers=self.header_generate(), usage_point_id=usage_point_id).get()
  File "/app/models/query_detail.py", line 199, in get
    if "exit" in response:
       ^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
2024-07-03 13:23:16.557 -    ERROR : Erreur lors de la récupération de la consommation détaillée
2024-07-03 13:23:16.557 -    ERROR : argument of type 'NoneType' is not iterable
2024-07-03 13:23:16.557 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-07-03 13:23:16.557 -     INFO : [--] RÉCUPÉRATION DE LA PRODUCTION JOURNALIÈRE :
2024-07-03 13:23:16.557 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-07-03 13:23:16.557 -     INFO : Récupération de la production journalière désactivée sur le point de livraison
2024-07-03 13:23:16.557 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-07-03 13:23:16.557 -     INFO : [--] RÉCUPÉRATION DE LA PRODUCTION DÉTAILLÉE :
2024-07-03 13:23:16.557 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-07-03 13:23:16.557 -     INFO : Récupération de la production détaillée désactivée sur le point de livraison
2024-07-03 13:23:16.557 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-07-03 13:23:16.557 -     INFO : [22398842234758] RÉCUPÉRATION DE LA PUISSANCE MAXIMUM JOURNALIÈRE :
2024-07-03 13:23:16.557 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-07-03 13:23:16.562 -     INFO : Récupération des données : 2024-05-15 => 2024-07-05
2024-07-03 13:23:16.631 -     INFO :  Chargement des données depuis MyElectricalData 2024-05-15 => 2024-07-05
2024-07-03 13:23:17.075 -    ERROR : 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/app/models/query_power.py", line 67, in run
    interval_reading = meter_reading["interval_reading"]
                       ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
ycle: 14400
debug: true
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
home_assistant_ws:
  enable: true
  max_date: '2022-05-01'
  purge: false
  ssl: true
  token: --
  url: --
influxdb:
  batching_options:
    batch_size: 1000
    exponential_base: 2
    flush_interval: 1000
    jitter_interval: 0
    max_retries: 5
    max_retry_delay: 125000
    max_retry_time: 180000
    retry_interval: 5000
  bucket: myelectricaldata
  enable: false
  hostname: influxdb
  method: synchronous
  org: myelectricaldata
  port: 8086
  token: myelectricaldata
log2file: false
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: core-mosquitto
  password: led0zep1
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: nicolas
myelectricaldata:
  '--':
    cache: true
    consumption: true
    consumption_detail: true
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_max_power: true
    consumption_price_base: 0.229
    consumption_price_hc: 0.0
    consumption_price_hp: 0.0
    enable: true
    name: Linky
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    production: false
    production_detail: false
    production_detail_max_date: ''
    production_max_date: ''
    production_price: 0.0
    refresh_addresse: true
    refresh_contract: true
    token: --
tempo:
  enable: true
  price_blue_hc: 0.097
  price_blue_hp: 0.1249
  price_red_hc: 0.1216
  price_red_hp: 0.6712
  price_white_hc: 0.114
  price_white_hp: 0.1508
wipe_influxdb: false
```
</details>

**Type d'installation**

- [ ] Docker
- [x] HassIO

**Version : 0.13.2**
