### ISSUE TITLE
usage de la fonction on_event dépréciée  

### ISSUE THREAD

**Issue by alainvdu69** [MyElectricalData/myelectricaldata_import#555]
Bonjour,

Suite à la relance après la longue panne, j'ai ça dans le log au début du démarrage :
/app/main.py:93: DeprecationWarning: 
        on_event is deprecated, use lifespan event handlers instead.

        Read more about it in the
        [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
        
  @APP.on_event("startup")
/app/main.py:99: DeprecationWarning: 
        on_event is deprecated, use lifespan event handlers instead.

        Read more about it in the
        [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
        
  @APP.on_event("startup")
/app/main.py:105: DeprecationWarning: 
        on_event is deprecated, use lifespan event handlers instead.

        Read more about it in the
        [FastAPI docs for Lifespan Events](https://fastapi.tiangolo.com/advanced/events/).
        
  @APP.on_event("startup")

<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 7200
debug: false
home_assistant:
  card_myenedis: true
  discovery: true
  discovery_prefix: homeassistant
  enable: true
influxdb:
  batching_options:
    batch_size: 1000
    exponential_base: 2
    flush_interval: 1000
    jitter_interval: 0
    max_retries: 5
    max_retry_delay: 125000
    max_retry_time: 180000
    retry_interval: 5000
  bucket: myelectricaldata/autogen
  enable: true
  hostname: 11.6.168.112
  method: asynchronous
  org: '-'
  port: 8086
  token: myelectricaldata:myelectricaldata
tempo:
  enable: true
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: 11.6.168.112
  password: myelectricaldata
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: myelectricaldata
myelectricaldata:
  '19177713414365':
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_price_base: '0.2516'
    consumption_price_hc: '0.2068'
    consumption_price_hp: '0.2700'
    enable: 'true'
    name: Studio
    offpeak_hours_0: 22H00-6H00
    offpeak_hours_1: 22H00-6H00
    offpeak_hours_2: 22H00-6H00
    offpeak_hours_3: 22H00-6H00
    offpeak_hours_4: 22H00-6H00
    offpeak_hours_5: 22H00-6H00
    offpeak_hours_6: 22H00-6H00
    plan: BASE
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: ''
    production_max_date: ''
    refresh_addresse: 'false'
    refresh_contract: 'false'
    token: sh_xzF1zz1Epxghg4pDrZS4=
  '19177858132189':
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_max_power: 'true'
    consumption_price_base: '0.2516'
    consumption_price_hc: '0.2068'
    consumption_price_hp: '0.2700'
    enable: 'true'
    name: Appart
    offpeak_hours_0: 22H00-6H00
    offpeak_hours_1: 22H00-6H00
    offpeak_hours_2: 22H00-6H00
    offpeak_hours_3: 22H00-6H00
    offpeak_hours_4: 22H00-6H00
    offpeak_hours_5: 22H00-6H00
    offpeak_hours_6: 22H00-6H00
    plan: BASE
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: ''
    production_max_date: ''
    production_price: '0.0'
    refresh_addresse: 'false'
    refresh_contract: 'false'
    token: SJlBqRA55P7iSHdwA=
wipe_cache: false
wipe_influxdb: false

```

**Type d'installation**

- [ ] Docker
- [ X ] HassIO

**Version : 0.13.2**
