### ISSUE TITLE
[BUG] - probleme recup info contractuelle et info postales

### ISSUE THREAD

**Issue by dudu7731** [MyElectricalData/myelectricaldata_import#570]
**Description du bug**
après avoir vidé le cache cela donne ça :

━━━━━━━━━━━━
2024-08-14 10:17:22.890 -     INFO : [xxxx] RÉCUPÉRATION DES INFORMATIONS CONTRACTUELLES :
2024-08-14 10:17:22.890 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-08-14 10:17:22.900 -     INFO :  =>  Pas de cache
2024-08-14 10:17:23.946 -    ERROR : {'error': True, 'description': "Erreur lors de la récupération des données d'Enedis, merci de réessayer plus tard - Code d'erreur : 500 (cf. F.A.Q pour les codes d'erreurs)"}
2024-08-14 10:17:23.946 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ TERMINE ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-08-14 10:17:23.947 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-08-14 10:17:23.947 -     INFO : [xxxxx] RÉCUPÉRATION DES COORDONNÉES POSTALES :
2024-08-14 10:17:23.947 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ ❖ ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2024-08-14 10:17:23.954 -     INFO :  =>  Pas de cache
2024-08-14 10:17:24.916 -    ERROR : {'error': True, 'description': "Erreur lors de la récupération des données d'Enedis, merci de réessayer plus tard - Code d'erreur : 500 (cf. F.A.Q pour les codes d'erreurs)"}
2024-08-14 10:17:24.916 -     INFO : ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ◦ TERMINE ◦ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 14400
debug: false
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
home_assistant_ws:
  enable: false
  max_date: '2021-01-01'
  purge: false
  ssl: true
  token: XXXXXXXXXXXXXXXX
  url: XXXXXXXXXX
influxdb:
  bucket: MyElectricalData
  enable: true
  hostname: XXXXXXXXXX
  method: batching
  org: production
  port: 8086
  scheme: http
  token: XXXXXXXXXXXXXXXXX
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname:XXXXXXXXX
  password: XXXXXXXXXXXX
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: XXXXXXX
myelectricaldata:
  'XXXXXXX':
    activation_date_daily: ''
    activation_date_detail: ''
    cache: true
    consumption: true
    consumption_detail: true
    consumption_detail_max_date: '2022-01-01'
    consumption_max_date: '2022-01-01'
    consumption_max_power: true
    consumption_price_base: 0.2516
    consumption_price_hc: 0.2068
    consumption_price_hp: 0.27
    enable: true
    name: Home Enedis
    offpeak_hours_0: 22h00-06h00
    offpeak_hours_1: 22h00-06h00
    offpeak_hours_2: 22h00-06h00
    offpeak_hours_3: 22h00-06h00
    offpeak_hours_4: 22h00-06h00
    offpeak_hours_5: 22h00-06h00
    offpeak_hours_6: 22h00-06h00
    plan: Tempo
    production: false
    production_detail: false
    production_detail_max_date: ''
    production_max_date: ''
    production_price: 0.0
    refresh_addresse: true
    refresh_contract: false
    token: XXXXXXXXXXXXXXXXXXXXX
tempo:
  enable: true
wipe_cache: false
wipe_influxdb: false

```
</details>

**Type d'installation**

- [ ] Docker
- [ x] HassIO

**Version : 0.13.2**
