### ISSUE TITLE
[HELP] - Pas de données dans "Energy dashboard"

### ISSUE THREAD

**Issue by mnapoli** [MyElectricalData/myelectricaldata_import#572]
J'ai bien 3 métriques qui apparaissent via MQTT, donc cela fonctionne.

<img width="1243" alt="Screen-002011" src="https://github.com/user-attachments/assets/88b942e2-57a8-4e66-b897-6148e4fe910c">

J'ai également toutes les données dans le dashboard MyElectricalData intégré à HA, y compris les données horaires.

Mais rien d'autre, rien dans le dashboard Energy. D'après la doc je ne suis pas sur : est-ce normal ?
(pour être honnête je ne comprends pas comment une métrique HA peut être créé via l'URL websocket, ça n'est pas une intégration comme MQTT ou autre, mais je m'égare peut-être)

Est-ce que des métriques doivent apparaitre qqpart ? Ou directement dans le dashboard Energy ?

Ma config : 

```yaml
cycle: 14400 # 4H
debug: false
log2file: false
wipe_influxdb: false # Work only with influxdb > 2.X
# Par défaut le backend en local dans le /data/cache.db du conteneur.
# Mais il est possible de basculer sur une base de données externe de type SQLite ou PostgreSQL
# Exemple pour Postgres :
# storage_uri: postgresql://myelectricaldata:myelectricaldata@postgres:5432/myelectricaldata
mqtt:
  enable: true
  hostname: core-mosquitto
  port: 1883
  username: myelectricaldata
  password: myelectricaldata
  prefix: myelectricaldata
  client_id: myelectricaldata # DOIT ETRE UNIQUE SUR LA TOTALITE DES CLIENTS CONNECTE AU SERVEUR MQTT
  retain: true
  qos: 0
home_assistant: # MQTT est obligatoire pour Home Assistant
  enable: true
  discovery: true
  discovery_prefix: homeassistant
home_assistant_ws:
  enable: true
  ssl: false
  token: xxxxx
  url: homeassistant.local
influxdb:
  enable: false
myelectricaldata:
  "xxxxxx":
    enable: "true"
    token: "xxxxx="
    name: "Maison"
    addresses: "true"
    cache: "true"
    consumption: "true"
    consumption_detail: "true"
    consumption_price_base: "0.2516"
    consumption_price_hc: "0.2068"
    consumption_price_hp: "0.27"
    #consumption_max_date: "2021-06-01"
    #consumption_detail_max_date: "2021-06-01"
    offpeak_hours_0: "1H34-7H34;14H34-16H34" # LUNDI
    offpeak_hours_1: "1H34-7H34;14H34-16H34" # MARDI
    offpeak_hours_2: "1H34-7H34;14H34-16H34" # MERCREDI
    offpeak_hours_3: "1H34-7H34;14H34-16H34" # JEUDI
    offpeak_hours_4: "1H34-7H34;14H34-16H34" # VENDREDI
    offpeak_hours_5: "1H34-7H34;14H34-16H34" # SAMEDI
    offpeak_hours_6: "1H34-7H34;14H34-16H34" # DIMANCHE
    plan: HC/HP
    production: "false"
    production_detail: "false"
    production_price: "0.0"
    production_max_date: "2021-06-01"
    production_detail_max_date: "2021-06-01"
    refresh_addresse: "false"
    refresh_contract: "false"
```

J'ai un doute sur la config `home_assistant_ws`. Est-ce `homeassistant.local` qui est pas bon ? C'est l'URL que j'utilise pour accéder à HA sur mon réseau (plus exactement `http://homeassistant.local:8123/`).

Merci pour l'aide !
