### ISSUE TITLE
[BUG] - WSS SSL WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by SylvainDx** [MyElectricalData/myelectricaldata_import#576]
**Description du bug**
Merci de me détailler au mieux le bug et une procédure pour le reproduire si possible.

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
port: 5000
debug: true
log2file: false
wipe_influxdb: false # Work only with influxdb > 2.X
# Par défaut le backend en local dans le /data/cache.db du conteneur.
# Mais il est possible de basculer sur une base de données externe de type SQLite ou PostgreSQL
# Exemple pour Postgres :
# storage_uri: postgresql://myelectricaldata:myelectricaldata@postgres:5432/myelectricaldata
tempo:
  enable: true
home_assistant: # WITH MQTT DISCOVERY
  enable: true
  discovery: true
  discovery_prefix: homeassistant
home_assistant_ws: # FOR ENERGY TAB
  enable: true
  ssl: true
  token: ##########_Token de connexion_Home_Assitant
  url: 192.168.1.###:8123
ssl:
  gateway: True
  certfile: ""
  keyfile: ""
influxdb:
  enable: false
  hostname: influxdb
  port: 8086
  token: myelectricaldata
  org: myelectricaldata
  bucket: myelectricaldata
  # ATTENTION, L'activation de l'importation asynchrone va réduire fortement le temps d'importation dans InfluxDB
  # mais va augmenter la consommation mémoire & CPU et donc à activer uniquement sur un hardware robuste.
  method: synchronous    # Mode disponible : synchronous / asynchronous / batching
  # batching_options permet uniquement de configurer la methode `batching`.
  # Pour plus d'information : https://github.com/influxdata/influxdb-client-python#batching
  batching_options:
    batch_size: 1000
    flush_interval: 1000
    jitter_interval: 0
    retry_interval: 5000
    max_retry_time: 180_000
    max_retries: 5
    max_retry_delay: 125_000
    exponential_base: 2
mqtt:
  enable: true
  hostname: 192.168.1.###
  port: 1883
  username: ########
  password: ########
  prefix: myelectricaldata
  client_id: myelectricaldata     # DOIT ETRE UNIQUE SUR LA TOTALITE DES CLIENTS CONNECTE AU SERVEUR MQTT
  retain: true
  qos: 0
# Configuration SSL optionnel.
#ssl:
#  keyfile: "/data/key.pem"
#  certfile: "/data/cert.pem"
myelectricaldata:
  "MON_PDL_1":
    enable: 'true'
    token: ####_pdl
    name: "Maison"
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_price_base: '0.145907'
    consumption_price_hc: '0.124364'
    consumption_price_hp: '0.164915'
    consumption_max_date: "2021-06-01"
    consumption_detail_max_date: "2021-06-01"
    offpeak_hours_0: 22H00-6H00               # LUNDI
    offpeak_hours_1: 22H00-6H00               # MARDI
    offpeak_hours_2: 22H00-6H00               # MERCREDI
    offpeak_hours_3: 22H00-6H00               # JEUDI
    offpeak_hours_4: 22H00-6H00               # VENDREDI
    offpeak_hours_5: 22H00-6H00;12H00-14H00   # SAMEDI
    offpeak_hours_6: 22H00-6H00;12H00-14H00   # DIMANCHE
    plan: HC/HP
    production: 'false'
    production_detail: 'false'
    production_price: '0.0'
    production_max_date: "2021-06-01"
    production_detail_max_date: "2021-06-01"
    refresh_addresse: 'false'
    refresh_contract: 'false'
```
</details>

**Type d'installation**

- [x] Docker
- [ ] HassIO

**Version : X.X.X**

2024-10-24 15:11:17.763 -     INFO : [MON_PDL_1] IMPORT DES DONNÉES VERS L'ONGLET ENERGY DE HOME ASSISTANT (WEBSOCKET)
2024-10-24 15:11:17.772 -     INFO : Connexion au WebSocket Home Assistant wss://192.168.1.16:8123/api/websocket
2024-10-24 15:11:17.818 -    ERROR : [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1000)
2024-10-24 15:11:17.819 - CRITICAL : Connexion impossible vers Home Assistant
