### ISSUE TITLE
[BUG] - Calcul consommation de la veille

### ISSUE THREAD

**Issue by LGO44** [MyElectricalData/myelectricaldata_import#580]
**Description du bug**
La conso de la veille ne semble pas calculée, elle le sera demain cf screen-shot joint
idem pour la puissance max d'hier

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 10800
debug: true
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
home_assistant_ws:
  enable: false
  ssl: false
influxdb:
  bucket: myelectricaldata/RETENTION
  enable: true
  hostname: xxxxxxxx
  method: asynchronous
  org: "-"
  port: 8086
  token: xxxxxxxxxxxxxxxx:yyyyyyyyyyyy
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: xxxxxxxxxxxxxx
  password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: homeassistant
myelectricaldata:
  "14xxxxxx9":
    activation_date_daily: ""
    activation_date_detail: ""
    addresses: true
    cache: "true"
    consumption: "true"
    consumption_detail: "true"
    consumption_detail_max_date: "2021-03-05"
    consumption_max_date: "2021-03-05"
    consumption_max_power: "true"
    consumption_price_base: "0.2460"
    consumption_price_hc: "0.1828"
    consumption_price_hp: "0.2460"
    enable: "true"
    name: 
    offpeak_hours_0: 01h30-07h30;12h30-14h30
    offpeak_hours_1: 01h30-07h30;12h30-14h30
    offpeak_hours_2: 01h30-07h30;12h30-14h30
    offpeak_hours_3: 01h30-07h30;12h30-14h30
    offpeak_hours_4: 01h30-07h30;12h30-14h30
    offpeak_hours_5: 01h30-07h30;12h30-14h30
    offpeak_hours_6: 01h30-07h30;12h30-14h30
    plan: HC/HP
    production: "false"
    production_detail: "false"
    production_detail_max_date: ""
    production_max_date: ""
    production_price: "0.0"
    refresh_addresse: "false"
    refresh_contract: "false"
    token: xxxxxxxxxxxxxxxxx
```
</details>

**Type d'installation**

-Core                                  2024.11.2
Supervisor                        2024.11.2
Operating System            13.2
Interface utilisateur        20241106.2

**Version : 0.13.2 **

![image](https://github.com/user-attachments/assets/c1df10f5-6f64-4cfd-a3a6-d440d6d07776)
