### ISSUE TITLE
[BUG] - 

### ISSUE THREAD

**Issue by SylvainDx** [MyElectricalData/myelectricaldata_import#584]
**Description du bug**
Dans le tableau de bord HA, sur le créneau Horaire 23h-00h, des données remonte sur le compteur HC du matin
Visible systématiquement lors de changement de couleur.
![image](https://github.com/user-attachments/assets/a23d1486-2530-4f46-9d2a-1d6df7508e68)
![image](https://github.com/user-attachments/assets/24b379a3-f8af-45a1-9713-7fb3e08618b6)

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
backend:
  uri: sqlite:////data/myelectricaldata.db
debug: true
gateway:
  ssl: true
  url: myelectricaldata.fr
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
home_assistant_ws:
  enable: true
  ssl: false
  token: ####
  url: 192.168.1.###:8123
influxdb:
  enable: false
logging:
  debug: true
  log2file: true
  log_format: '%(asctime)s.%(msecs)03d - %(levelname)8s : %(message)s'
  log_format_date: '%Y-%m-%d %H:%M:%S'
  log_http: false
  log_level: 20
mqtt:
  cert: false
  client_id: myelectricaldata
  enable: true
  hostname: mosquitto
  password: ####
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: ####
myelectricaldata:
  'MON_PDL':
    cache: true
    consumption: true
    consumption_detail: true
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_max_power: true
    consumption_price_base: 0.2516
    consumption_price_hc: 0.2068
    consumption_price_hp: 0.27
    enable: true
    name: LinkyDx
    offpeak_hours_0: 22H00-6H00
    offpeak_hours_1: 22H00-6H00
    offpeak_hours_2: 22H00-6H00
    offpeak_hours_3: 22H00-6H00
    offpeak_hours_4: 22H00-6H00
    offpeak_hours_5: 22H00-6H00
    offpeak_hours_6: 22H00-6H00
    plan: Tempo
    production: false
    production_detail: false
    production_detail_max_date: ''
    production_max_date: ''
    production_price: 0.0
    refresh_addresse: true
    refresh_contract: false
    token: ####=
opentelemetry:
  enable: false
server:
  certfile: ''
  cidr: 0.0.0.0
  cycle: 14400
  keyfile: ''
  port: 5000
tempo:
  enable: true

```
</details>

**Type d'installation**

- [x] Docker
- [ ] HassIO

**Version : 0.13.2**
