### ISSUE TITLE
[BUG] -

### ISSUE THREAD

**Issue by GillesMattioli** [MyElectricalData/myelectricaldata_import#589]
**Description du bug**
Un message d'erreur apparait dans le journal ha , depuis la version core 2025-1-0
State attributes for sensor.linky_21256874049122_consumption_last5day exceed maximum size of 16384 bytes. This can cause database performance issues; Attributes will not be stored
et du coup l'affichage dans la carte linky est faux (manque 1 jour)

![Image](https://github.com/user-attachments/assets/8a7a667b-06e7-449f-83cb-1c8e1fdefe41)

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
RENSEIGNE TON FICHIER DE CONFIG SANS PDL & TOKEN
myelectricaldata:
  'XXXXXXXXXXX22':
    activation_date_daily: ''
    activation_date_detail: ''
    cache: true
    consumption: true
    consumption_detail: true
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_max_power: true
    consumption_price_base: 0.2517
    consumption_price_hc: 0.0
    consumption_price_hp: 0.0
    enable: true
    name: Maison
    offpeak_hours_0: ''
    offpeak_hours_1: ''
    offpeak_hours_2: ''
    offpeak_hours_3: ''
    offpeak_hours_4: ''
    offpeak_hours_5: ''
    offpeak_hours_6: ''
    plan: BASE
    production: false
    production_detail: false
    production_detail_max_date: ''
    production_max_date: ''
    production_price: 0.0
    refresh_addresse: false
    refresh_contract: false
    token: zzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
```
</details>

**Type d'installation**

- [ ] Docker
- [ x] HassIO core 

**Version : 0.13.2**
