### ISSUE TITLE
[BUG] - Récupération impossible des donnnées

### ISSUE THREAD

**Issue by Tandonnet** [MyElectricalData/myelectricaldata_import#592]
**Description du bug**
Depuis quelques temps, aucune donnée n'est récupérée et à chaque lancement de l'image, les logs affichent "Suppression du point de livraison" et aucune donnée n'est récupérée.
L'erreur apparait également sur d'autres clients docker avec une clean install avec la même config.

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 14400
debug: true
home_assistant:
  discovery: true
  discovery_prefix: homeassistant
  enable: true
influxdb:
  enable: false
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: homeassistant
  password: ********
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: myelectricaldata
myelectricaldata:
  PDL:
    addresses: "true"
    cache: "true"
    consumption: "true"
    consumption_detail: "true"
    consumption_detail_max_date: ""
    consumption_max_date: ""
    consumption_max_power: "true"
    consumption_price_base: "0.1992"
    consumption_price_hc: "0.0"
    consumption_price_hp: "0.0"
    enable: "true"
    name: Home
    offpeak_hours_0: ""
    offpeak_hours_1: ""
    offpeak_hours_2: ""
    offpeak_hours_3: ""
    offpeak_hours_4: ""
    offpeak_hours_5: ""
    offpeak_hours_6: ""
    plan: BASE
    production: "false"
    production_detail: "false"
    production_detail_max_date: ""
    production_max_date: ""
    production_price: "0.0"
    refresh_addresse: "true"
    refresh_contract: "false"
    token: "*********"
```
</details>

**Type d'installation**

- [X] Docker
- [X] HassIO

**Version : 0.13.2**
