### ISSUE TITLE
[BUG] - Absence des données journalières et dashboard Energy vide

### ISSUE THREAD

**Issue by avidflyer17** [MyElectricalData/myelectricaldata_import#594]
**Description du bug**
Bonjour,
Depuis ce matin, je n'ai pas de donnée journalière dans le dashboard Energy. J'ai tenté de relancer le conteneur ou de réimporter depuis le front WEB, rien n'y fait. Date de mise à jour : il y a 21 heure. La consommation journalière détaillée semble être absente.

Dans les logs, on peut voir que le 13/02 n'est pas inclus. Est-ce un souci côté Enedis ?

2025-02-14 13:21:39.755 -     INFO : Envoi des données de conso WHITEHP vers Home Assistant 1/1 (2025-02-12T21:00:00+01:00 => 2024-04-24T07:00:00+02:00)
2025-02-14 13:21:39.769 -     INFO : - sensor.linky_xxxxxxx_whitehp_consumption
2025-02-14 13:21:39.772 -     INFO : Envoi des données de conso WHITEHC vers Home Assistant 1/1 (2025-02-12T23:00:00+01:00 => 2024-04-24T22:00:00+02:00)
2025-02-14 13:21:39.785 -     INFO : - sensor.linky_xxxxxxx_whitehc_consumption

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
backend:
  uri: sqlite:////data/myelectricaldata.db
gateway:
  ssl: true
  url: myelectricaldata.fr
home_assistant:
  discovery_prefix: homeassistant
  enable: true
home_assistant_ws:
  batch_size: 1000
  enable: true
  max_date: '2022-01-01'
  purge: false
  ssl: false
  token: xxxxxxxxx
  url: 192.168.1.30:8123
influxdb:
  batching_options:
    batch_size: 1000
    exponential_base: 2
    flush_interval: 1000
    jitter_interval: 0
    max_retries: 5
    max_retry_delay: '125_000'
    max_retry_time: '180_000'
    retry_interval: 5000
  bucket: mybucket
  enable: false
  hostname: localhost
  method: synchronous
  org: myorg
  port: 8086
  scheme: http
  timezone: UTC
  token: my-token
  wipe: false
logging:
  debug: false
  log2file: false
  log_format: '%(asctime)s.%(msecs)03d - %(levelname)8s : %(message)s'
  log_format_date: '%Y-%m-%d %H:%M:%S'
  log_http: false
  log_level: 20
mqtt:
  cert: false
  client_id: myelectricaldata
  enable: true
  hostname: mqtt5
  password: xxxxxxx
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: myelectricaldata
myelectricaldata:
  'PDL':
    cache: true
    consumption: true
    consumption_detail: true
    consumption_detail_max_date: '2024-01-01'
    consumption_max_date: '2022-01-01'
    consumption_max_power: true
    consumption_price_base: 0.0
    consumption_price_hc: 0.0
    consumption_price_hp: 0.0
    enable: true
    name: Maison
    offpeak_hours_0: 22h00-6h00
    offpeak_hours_1: 22h00-6h00
    offpeak_hours_2: 22h00-6h00
    offpeak_hours_3: 22h00-6h00
    offpeak_hours_4: 22h00-6h00
    offpeak_hours_5: 22h00-6h00
    offpeak_hours_6: 22h00-6h00
    plan: Tempo
    production: false
    production_detail: false
    production_detail_max_date: '2025-01-13'
    production_max_date: '2025-01-13'
    production_price: 0.13
    refresh_addresse: true
    refresh_contract: true
    token: xxxxxx
opentelemetry:
  enable: false
  endpoint: http://localhost:4317
  environment: production
  extension:
  - sqlalchemy
  - fastapi
  service_name: myelectricaldata
server:
  certfile: ''
  cidr: 0.0.0.0
  cycle: 14400
  keyfile: ''
  port: 5000

```
</details>

**Type d'installation**

- [ x] Docker
- [ ] HassIO

**Version : v0.13.2**

<img width="1534" alt="Image" src="https://github.com/user-attachments/assets/dbf73d47-0d48-460f-9f85-512fd9db1911" />

<img width="1543" alt="Image" src="https://github.com/user-attachments/assets/e7ab8bc1-ab56-457d-8e08-f457498fc3ca" />
