### ISSUE TITLE
[BUG] - calcul du coût de la veille à 0

### ISSUE THREAD

**Issue by alainvdu69** [MyElectricalData/myelectricaldata_import#598]
Bonjour,
Depuis un certain temps, j'ai le souci décrit dans le titre.
C'est visible sur la carte MyElectricalData :

![Image](https://github.com/user-attachments/assets/d4505581-7bcd-4832-afdb-b5f5ba1467e0)

Et aussi sur les données du sensor :
Le coût HC et HP sont de 0.7 et 0.9, et le cumul est à 0
 
dailyweek_cost: **0**, 1.6, 1.9, 1.8, 2, 2.6, 2.4
dailyweek_costHP: **0.9**, 0.9, 1.1, 1, 1.2, 1.8, 1.6
dailyweek_HP: 4.21, 4.59, 5.54, 4.92, 6.09, 9.05, 7.73
dailyweek_costHC: **0.7**, 0.7, 0.8, 0.8, 0.8, 0.8, 0.8
dailyweek_HC: 3.43, 3.43, 3.84, 3.87, 3.92, 3.81, 4.1

J'ai 2 PDL configurés, et même pb sur les 2.

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
cycle: 7200
debug: false
home_assistant:
  card_myenedis: true
  discovery: true
  discovery_prefix: homeassistant
  enable: true
influxdb:
  batching_options:
    batch_size: 1000
    exponential_base: 2
    flush_interval: 1000
    jitter_interval: 0
    max_retries: 5
    max_retry_delay: 125000
    max_retry_time: 180000
    retry_interval: 5000
  bucket: myelectricaldata/autogen
  enable: true
  hostname: 11.6.168.112
  method: asynchronous
  org: '-'
  port: 8086
  token: myelectricaldata:myelectricaldata
tempo:
  enable: true
mqtt:
  client_id: myelectricaldata
  enable: true
  hostname: 11.6.168.112
  password: myelectricaldata
  port: 1883
  prefix: myelectricaldata
  qos: 0
  retain: true
  username: myelectricaldata
myelectricaldata:
  '1914365':
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_price_base: '0.2016'
    consumption_price_hc: '0.2068'
    consumption_price_hp: '0.2700'
    enable: 'true'
    name: Studio
    offpeak_hours_0: 22H00-6H00
    offpeak_hours_1: 22H00-6H00
    offpeak_hours_2: 22H00-6H00
    offpeak_hours_3: 22H00-6H00
    offpeak_hours_4: 22H00-6H00
    offpeak_hours_5: 22H00-6H00
    offpeak_hours_6: 22H00-6H00
    plan: BASE
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: ''
    production_max_date: ''
    refresh_addresse: 'false'
    refresh_contract: 'false'
    token: sh_xzF1zzmhg4pDrZS4=
  '1917189':
    addresses: 'true'
    cache: 'true'
    consumption: 'true'
    consumption_detail: 'true'
    consumption_detail_max_date: ''
    consumption_max_date: ''
    consumption_max_power: 'true'
    consumption_price_base: '0.2016'
    consumption_price_hc: '0.2068'
    consumption_price_hp: '0.2700'
    enable: 'true'
    name: Appart
    offpeak_hours_0: 22H00-6H00
    offpeak_hours_1: 22H00-6H00
    offpeak_hours_2: 22H00-6H00
    offpeak_hours_3: 22H00-6H00
    offpeak_hours_4: 22H00-6H00
    offpeak_hours_5: 22H00-6H00
    offpeak_hours_6: 22H00-6H00
    plan: BASE
    production: 'false'
    production_detail: 'false'
    production_detail_max_date: ''
    production_max_date: ''
    production_price: '0.0'
    refresh_addresse: 'false'
    refresh_contract: 'false'
    token: SJlBqRAR65n55P7iSHdwA=
wipe_cache: false
wipe_influxdb: false

```
</details>

**Type d'installation**

- [ ] Docker
- [X] HassIO

**Version : 0.13.2**
