### ISSUE TITLE
[BUG] - Error running job

### ISSUE THREAD

**Issue by Titou84240** [MyElectricalData/myelectricaldata_import#600]
**Description du bug**
Bonjour , j'ai detecté l'erreur suivant dans mes journaux , qui ne semble pas affecter le module (ou du moins je ne le vois pas) : 

nregistreur: homeassistant.core
Source: core.py:1577
S'est produit pour la première fois: 12:02:53 (1 occurrences)
Dernier enregistrement: 12:02:53

Error running job: <Job onetime listen homeassistant_start <function _async_at_core_state.<locals>._matched_event at 0x7fcea4a9f6a0> HassJobType.Callback <_OneTimeListener homeassistant.helpers.start:<function _async_at_core_state.<locals>._matched_event at 0x7fcea4a9f6a0>>>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 635, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: '9 kVA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 638, in state
    numerical_value = float(value)
ValueError: could not convert string to float: '9 kVA'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1577, in async_fire_internal
    self._hass.async_run_hass_job(job, event)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 940, in async_run_hass_job
    hassjob.target(*args)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 1438, in __call__
    self.hass.async_run_hass_job(self.listener_job, event)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 940, in async_run_hass_job
    hassjob.target(*args)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/start.py", line 44, in _matched_event
    hass.async_run_hass_job(at_start_job, hass)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 940, in async_run_hass_job
    hassjob.target(*args)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 517, in _async_template_startup
    result_info.async_refresh()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1126, in async_refresh
    self._refresh(None)
    ~~~~~~~~~~~~~^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 1312, in _refresh
    self.hass.async_run_hass_job(self._job, event, updates)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 940, in async_run_hass_job
    hassjob.target(*args)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/template/template_entity.py", line 463, in _handle_results
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 642, in state
    raise ValueError(
    ...<5 lines>...
    ) from err
ValueError: Sensor sensor.myelectricaldata_subscribed_power has device class 'None', state class 'None' unit 'KVa' and suggested precision 'None' thus indicating it has a numeric value; however, it has the non-numeric value: '9 kVA' (<class 'str'>)


Je ne sais pas bien quoi faire , pouvez-vous m'aider svp ?

<details>
<summary>Configuration (config.yaml)</summary>

```yaml
# Loads default set of integrations. Do not remove.
default_config:

wake_on_lan:

cover:
  - platform: template
    covers:
      stateful_rts_test_shutter:  # unique ID
        friendly_name: "Status portail" # your name
        optimistic: true # default when no state is available
        open_cover:
          - action: cover.open_cover
            target:
              entity_id: cover.portail_maison # change to your device id
        close_cover:
          - action: cover.close_cover
            target:
              entity_id: cover.portail_maison # change to your device id
        stop_cover:
          - action: cover.stop_cover
            target:
              entity_id: cover.portail_maison # change to your device id
        icon_template: >-
          {% if states('cover.portail_maison')|float > 0 %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24


# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/community/custom-brand-icons/custom-brand-icons.js 
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml # created by oc see saved files
binary_sensor: !include binary_sensor.yaml
  

notify: 
  name: "Titou-W11-NVME-ULTRA"
  platform: hass_agent_notifier
  resource: http://192.168.3.45:5118/notify

logger:
  default: warning
  logs:
    custom_components.hass_agent_notifier: debug

lovelace:
  mode: yaml
  resources: !include ui_lovelace_minimalist/resources/resources.yaml
  
#
```
</details>

**Type d'installation**

- [X] Docker
- [ ] HassIO

**Version : 28.0.1**
